feat: add confirm password to flutter_firebase_login example
felangel/bloc pull request #1835
Opened 2020-10-15 16:02 UTC by YJaff

## Status

**READY**

## Breaking Changes

NO

## Description

New attempt on adding a confirmedPassword field to the signUp screen of the flutter_firebase_login example, following your advices from my last pull request: https://github.com/felangel/bloc/pull/1812#discussion_r502670294
> I would recommend defining a ConfirmPassword `FormzInput` which has a dependency on the original password to perform the validation. See [ChicagoFlutter/formz#5](https://github.com/ChicagoFlutter/formz/issues/5) for more info.

I also added the required tests.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2020-10-18 04:25 UTC, felangel commented on examples/flutter_firebase_login/lib/authentication/models/models.dart
> +export 'confirmedPassword.dart';
```suggestion
export 'confirmed_password.dart';
```

2020-10-18 04:25 UTC, felangel commented on examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
> +import 'package:flutter_firebase_login/authentication/models/confirmedPassword.dart';
this import should not be needed because we should export `confirmed_password.dart` from the `authentication.dart` barrel file.

2020-10-18 04:26 UTC, felangel commented on examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
> +        original: password, value: state.confirmedPassword.value);
```suggestion
        original: password, value: state.confirmedPassword.value,);
```

nit but can we add a trailing comma and format for improved readability?

2020-10-18 04:26 UTC, felangel commented on examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
> +    //added
```suggestion
```

2020-10-18 04:26 UTC, felangel commented on examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
> +        ConfirmedPassword.dirty(original: state.password, value: value);
```suggestion
        ConfirmedPassword.dirty(original: state.password, value: value,);
```

2020-10-18 04:28 UTC, felangel requested changes
overall looks great just had a few requested changes. let me know what you think 👍

2020-10-18 19:58 UTC, YJaff commented
> overall looks great just had a few requested changes. let me know what you think 👍

I think we're good now, I just committed your changes 👌 Thanks for the review!

2020-10-20 18:22 UTC, felangel approved these changes
LGTM :shipit: 
Thanks so much for the contribution! 💯  🚀

2020-10-20 18:25 UTC, merged