added error handling (https://github.com/felangel/bloc/issues/2775)
felangel/bloc pull request #2783
Opened 2021-09-23 10:01 UTC by jasonjackson

## Status

**READY**

## Breaking Changes

NO

## Description

Added error handling on sign up, login with email and password, and sign up with google, per the following thread:

https://github.com/felangel/bloc/issues/2775

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [X] 🗑️ Chore

2021-09-23 10:43 UTC, jasonjackson commented
https://github.com/felangel/bloc/issues/2775

2021-09-23 15:39 UTC, felangel commented on examples/flutter_firebase_login/lib/login/view/login_form.dart
> +
```suggestion
```

2021-09-23 15:44 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +        await _firebaseAuth.createUserWithEmailAndPassword(
```suggestion
      await _firebaseAuth.createUserWithEmailAndPassword(
```

2021-09-23 15:44 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +
```suggestion
```

2021-09-23 15:44 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +
```suggestion
```

2021-09-23 15:46 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +  SignUpWithEmailAndPasswordFailure(this.message);
```suggestion
  SignUpWithEmailAndPasswordFailure(this.message);

  final String message;
```

2021-09-23 15:46 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +  LogInWithEmailAndPasswordFailure(this.message);
```suggestion
  LogInWithEmailAndPasswordFailure(this.message);

  final String message;
```

2021-09-23 15:46 UTC, felangel commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +  LogInWithGoogleFailure(this.message);
```suggestion
  LogInWithGoogleFailure(this.message);

  final String message;
```

2021-09-23 15:46 UTC, felangel commented on examples/flutter_firebase_login/lib/login/view/login_form.dart
> +import 'package:authentication_repository/authentication_repository.dart';
```suggestion
```

2021-09-24 04:28 UTC, jasonjackson commented
changes from code review merged to `jasonjackson:flutter_firebase_login_error_handling`

2021-09-29 20:52 UTC, marcossevilla requested changes
@jasonjackson great job, just a few comments about formatting to make it more readable and generic exception handling just to make it safer. 👍

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +      case 'invalid-email': return SignUpWithEmailAndPasswordFailure('Email is not valid or badly formatted.');
hi @jasonjackson, can you format this:
```dart
case 'invalid-email': return SignUpWithEmailAndPasswordFailure('Email is not valid or badly formatted.');
```
to this:
```dart
case 'invalid-email': 
  return SignUpWithEmailAndPasswordFailure('Email is not valid or badly formatted.');
```
so it's more readable on each case? Let me know what you think. 👍

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +      case 'account-exists-with-different-credential': return LogInWithGoogleFailure('Account exists with different credentials.');
Same for formatting here 👍

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +    } on FirebaseAuthException catch (e) {
I don't think we should remove `Exception` as it is a possibility that Firebase some time fails with a generic error, should be more like:
```dart
} on FirebaseAuthException catch (e) {
  throw SignUpWithEmailAndPasswordFailure.fromCode(e.code);
} on Exception {
  throw SignUpWithEmailAndPasswordFailure('Unknown');
}
```
What do you think?

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/lib/sign_up/cubit/sign_up_cubit.dart
> +    } on SignUpWithEmailAndPasswordFailure catch(e) {
This would have to handle a generic exception too, based on my comment below.

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +    } on FirebaseAuthException catch (e) {
Should handle generic exception too.

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart
> +    } on FirebaseAuthException catch (e) {
Should handle generic exception too.

2021-09-29 20:52 UTC, marcossevilla commented on examples/flutter_firebase_login/lib/login/cubit/login_cubit.dart
> +    } on LogInWithGoogleFailure catch (e) {
Should handle generic exception too.

2021-10-06 05:00 UTC, merged