docs: more consistent bloc in blocs_presentation.dart.md
felangel/bloc pull request #3751
Opened 2023-02-23 17:01 UTC by lsaudon

## Status

**READY**

## Breaking Changes

NO

## Description

`FirstBloc, FirstState` is more consistent in the example compared to  `WeatherCubit, WeatherState`

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

2023-02-24 21:53 UTC, tenhobi commented
Hi, how is that more consistent? `WeatherCubit` sound more like what it should do, so it is the right name IMO. What should maybe change are the names of other examples etc., if something more expressing could be used. But I see no issue in this case.

2023-02-24 21:55 UTC, lsaudon commented
This was just because WeatherCubit does not exist in the example.
Indeed, maybe do the opposite, find a more concrete name for SecondBloc.

2023-03-02 10:11 UTC, lsaudon commented
Maybe better?
- `ClothingBloc`, `ClothingBlocEvent`
- `WeatherBloc`, `RefreshWeather`

2023-03-06 05:41 UTC, felangel commented on docs/_snippets/architecture/blocs_presentation.dart.md
> +    return BlocListener<WeatherBloc, WeatherState>(
If we make this change we will also need to update the corresponding documentation in https://github.com/felangel/bloc/blob/b11fe6a1c00a5cb22fd38b2eba2ae6c0c773cec5/docs/architecture.md?plain=1#L73 (and other translations). The simpler change would be to go back to using `FirstBloc` and `SecondBloc` in order to be consistent with the rest of the docs. Let me know what you think and thanks for the contribution! 🙏

2023-03-06 05:41 UTC, felangel requested changes
See my comment and lmk what you think.

2023-03-11 20:16 UTC, tenhobi approved these changes

2023-03-20 14:42 UTC, felangel reviewed
LGTM thanks so much for the contribution! 💯

2023-03-20 14:42 UTC, merged